### ISSUE TITLE
Error packing from CLI

### ISSUE THREAD

**Issue by notbored** [oddoid/aseprite-atlas#4]
Followed instructions:
`npx aseprite-atlas-pack --sheet atlas.png --data atlas.json *.ase`

And result is:
`/Users/me/node_modules/.bin/aseprite-atlas-pack: line 4: exec: aseprite: not found`

Running macOS Catalina if that's of any help.

**Comment by notbored** [comment]
Figured it out, on macOS you need to call:

`/Applications/Aseprite.app/Contents/MacOS/aseprite`

not aseprite.

**Comment by niedzielski** [comment]
@notbored, the docs don't clarify this but it's expected that the path to the Asesprite binary, `/Applications/Aseprite.app/Contents/MacOS` in your case, is in your shell `PATH` environment variable. I can update the docs to give an example like:

    PATH="/Applications/Aseprite.app/Contents/MacOS:$PATH" npx aseprite-atlas-pack --sheet atlas.png --data atlas.json *.ase

However, users also need to be aware that `npx` is also assumed to be in the path:

    PATH="/Applications/Aseprite.app/Contents/MacOS:/your/path/to/node/bin:$PATH" npx aseprite-atlas-pack --sheet atlas.png --data atlas.json *.ase

Or to provide the full path to it:

    PATH="/Applications/Aseprite.app/Contents/MacOS:$PATH" /your/path/to/node/bin/npx aseprite-atlas-pack --sheet atlas.png --data atlas.json *.ase

**Comment by notbored** [comment]
I think updating the README would be helpful as others might assume, like I did, that things work without any configuration necessary.

Might save you the trouble of others opening issues in the future.
